spring.cloud:
  function:
    definition: supplier;consumer
  stream:
    bindings:
      consumer-in-0:
        destination: order-updated-new
      supplier-out-0:
        destination: order-created-new
    kafka:
      bindings:
        consumer-in-0:
          consumer:
            configuration:
              value:
                deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        supplier-out-0:
          producer:
            configuration:
              value:
                serializer: org.springframework.kafka.support.serializer.JsonSerializer
      binder:
        brokers:
          - localhost:9092
        configuration:
          default:
            spring.json.trusted.packages: com.restart.*